### ISSUE TITLE
clipse crashes during history search

### ISSUE THREAD

**Issue by cjk** [savedra1/clipse#164]
Thanks for making Clipse, I've been a happy user on Wayland for the last 6 months or so - it's the best :smiley: 

Now, sadly it stopped working for me today and I can't figure out why and how to fix it.

Once I open clipse (usually in Kitty) and start a history-search, if I type certain characters (like 's') it crashes immediately:

``` shell
❯ clipse keep
Caught panic:

runtime error: index out of range [1] with length 1

Restoring terminal...

goroutine 14 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
	runtime/debug/stack.go:18 +0x13
github.com/charmbracelet/bubbletea.(*Program).recoverFromPanic(0xc000254000)
	github.com/charmbracelet/bubbletea@v1.1.1/tea.go:705 +0x8b
panic({0x5ee72d4a2220?, 0xc00001e8b8?})
	runtime/panic.go:785 +0x132
github.com/sahilm/fuzzy.FindFromNoSort({0xc000015e84?, 0xc000012228?}, {0x5ee72d4bc8d0, 0xc000012228})
	github.com/sahilm/fuzzy@v0.1.1/fuzzy.go:136 +0x945
github.com/sahilm/fuzzy.FindFrom({0xc000015e84?, 0x3e8?}, {0x5ee72d4bc8d0?, 0xc000012228?})
	github.com/sahilm/fuzzy@v0.1.1/fuzzy.go:99 +0x25
github.com/sahilm/fuzzy.Find(...)
	github.com/sahilm/fuzzy@v0.1.1/fuzzy.go:83
github.com/charmbracelet/bubbles/list.DefaultFilter({0xc000015e84, 0x1}, {0xc000362008?, 0x8?, 0x0?})
	github.com/charmbracelet/bubbles@v0.20.0/list/list.go:89 +0x52
github.com/charmbracelet/bubbles/list.(*Model).handleFiltering.filterItems.func1()
	github.com/charmbracelet/bubbles@v0.20.0/list/list.go:1228 +0x1b5
github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1.1()
	github.com/charmbracelet/bubbletea@v1.1.1/tea.go:324 +0x7d
created by github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1 in goroutine 39
	github.com/charmbracelet/bubbletea@v1.1.1/tea.go:318 +0x131
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
	runtime/debug/stack.go:18 +0x13
github.com/savedra1/clipse/utils.HandleError({0x5ee72d4bbc20, 0xc000228980})
	github.com/savedra1/clipse/utils/err.go:11 +0x2c
main.launchTUI()
	github.com/savedra1/clipse/main.go:96 +0x77
main.main()
	github.com/savedra1/clipse/main.go:50 +0xc5
```

It's probably somehow related to my history-file, since if I delete it, the error goes away. But then my json-parser say the history-file is valid and clipse starts-up just fine. Only after searching for a specific history-entry, it crashes.

I'll try to narrow it down further, but I thought perhaps this is a general issue that should be fixed.

**Comment by savedra1** [comment]
Hi @cjk :wave: 

Thanks for the kind words, I'm glad to hear you've been enjoying clipse. Unfortunately this is a known issue that's caused by the fuzzy find algo _(within the BubbleTea TUI framework code)_ crashing when it encounters non-compatible characters in the history file, such as an irregular image binary pattern or a rare non-ascii text character. See issue #148.

As the part of the code that crashes is from the BubbleTea source it's difficult to implement fix but I will be looking into this as part of the next release. The fix in the meantime is to remove the non-compatible characters from the file. I'd recommend pinning anything you wouldn't want to lose and then running `clipse -clear`.  

I'll keep this issue open and update the FAQs. If you do identify the specific characters causing problems, please let me know here as that will be a big help towards finding a fix. 

Cheers

**Comment by cjk** [comment]
Ah, I see, yeah that makes sense. 
I'll then take a closer look at my clipboard-history and prune whatever looks suspicious.

Thanks for the tip!

If later there's a meaningful fix then the better, to prevent this from happening again. But I also understand that fixing 3rd-party libs isn't always fun / possible.

I'll keep enjoying clipse anyways! :1st_place_medal:

**Comment by sspaeti** [comment]
Unfortunately, I have these errors quite regularly too. Such unfortunate, as I love the clipboard tool too!

**Comment by savedra1** [comment]
> Unfortunately, I have these errors quite regularly too. Such unfortunate, as I love the clipboard tool too!

Hi @sspaeti, if you can provide some entries/chars you have that cause the crash, I can reproduce and have another look at a potential fix.

**Comment by Abhinav5383** [comment]
hi @savedra1,

It was crashing for me for a few days, so I binary searched through my fking long history and I have found a culprit
```json
{
    "value": "b\u0000l\u0000o\u0000b\u0000:\u0000h\u0000t\u0000t\u0000p\u0000s\u0000:\u0000/\u0000/\u0000w\u0000e\u0000b\u0000.\u0000w\u0000h\u0000a\u0000t\u0000s\u0000a\u0000p\u0000p\u0000.\u0000c\u0000o\u0000m\u0000/\u00004\u00006\u00002\u00003\u00000\u00008\u00005\u00004\u0000-\u00000\u00009\u0000d\u0000d\u0000-\u00004\u0000d\u00008\u00004\u0000-\u0000b\u00001\u0000d\u0000d\u0000-\u00002\u00006\u00002\u00004\u0000b\u00000\u00007\u0000a\u00004\u00007\u00000\u00002\u0000\n\u0000",
    "recorded": "2025-12-21 22:35:33.24722947",
    "filePath": "null",
    "pinned": false
}
```
not sure why the value is encoded like that, why are there null bytes between every character
the preview works just fine, only filter crashes

<img width="1069" height="198" alt="Image" src="https://github.com/user-attachments/assets/e5a9e6bb-0b49-4808-8649-2a1fb152cad7" />

I tried to copy similar URLs and it encoded these new ones just fine, Idk what happened with that one
hope it helps figure out the issue

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/7ac82288-edfe-41c1-81c2-76ba4a3f1298" />

**Comment by savedra1** [comment]
@Abhinav5383 thanks so much for that - I will see if i can use that to reproduce 👀

**Comment by savedra1** [comment]
I've merged a fix for the null byte character issue. You can also now run `clipse -clean` to fix any existing entries that contain this. 

I will leave this issue open, so that any other bad chars can be added to the sanitization logic (if found).
